- name: install unzip on my workstation
  tags: workstation
  package:
    name: unzip
    state: latest

- name: install terraform
  tags: workstation
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.3.4/terraform_1.3.4_linux_386.zip
    dest: /usr/local/bin
    remote_src: yes
    owner: root
    group: root
    mode: 0644

